import simpy

"""
Models an ISRU Plant that uses Hydrogen Reduction to generate LOX from lunar regolith.

References:
[1] https://doi.org/10.1073/pnas.2306146122 
"""
# -------------------------------------------------
# ISRU Plant Class Definition
# -------------------------------------------------

class ISRUPlant:
    def __init__(self, system, name, attributeDict):
        #self.processingRate = processingRate #kg/hr
        #self.regHeadGrade = regHeadGrade # wt% Ilmenite
        #self.energyConsumptionRate = energyConsumptionRate
        self.processingRate = attributeDict['processingRate']
        self.regHeadGrade = attributeDict['regHeadGrade']
        self.LOXStored = attributeDict['LOXStored']
        self.lg = attributeDict['lunarGravity'] #Acceleration due to gravity on the moon, m/(s^2)
        self.totalEnergyConsumed = attributeDict['totalEnergyConsumed']

        #Setup Energy Coeffecients / Constants for later
        self.excavationEnergyCoeff = attributeDict['excavationEnergyCoeff']
        self.transportEnergyCoeff = attributeDict['transportEnergyCoeff']
        self.liftHeight = attributeDict['liftHeight']
        self.gangueTransportDist = attributeDict['gangueTransportDist']
        self.reactorEnergyCoeff = attributeDict['reactorEnergyCoeff']
        self.electrolysisEnergyCoeff = attributeDict['electrolysisEnergyCoeff']
        self.liquefactionEnergyCoeff = attributeDict['liquefactionEnergyCoeff']

        self.processingUptime = 0 #Supposed to track how much time that ISRU plant spends processing regolith. Can be compared to with scenario run duration to determine plant uptime stat (MOE 2)
        self.totalLOXProduction = 0 #How much LOX was generated by the plant over the sim duration, NOT how much is stored at the plant
        self.regolithRecieved = 0 #How much regolith the plant recieved over the sim duration

        self.name = name
        #yield system.timeout(0)

    #Track Energy Consumption and how much LOX is generated by using this function. Note transportDist is how far the excavated regolith was transported to reach the ISRU plant.
    #All assumptions regarding effeciencies, reactor temperatures, etc made in [1] apply to this function.
    def processRegolith(self, system, regolithMass, transportDist=1):
        #Mass Related Attributes
        self.extractedLOXFraction = (0.51*0.47*31.999*self.regHeadGrade)/(2*151.71) #Equation 1 in [1]
        self.kgLOXPerHour = self.extractedLOXFraction*self.processingRate
        generatedLOX = self.extractedLOXFraction*regolithMass
        self.LOXStored += generatedLOX
        self.totalLOXProduction += generatedLOX
        self.regolithRecieved += regolithMass

        #Determine waste mass (gangue)
        m_bene_ilm = regolithMass*0.505*self.regHeadGrade #Eq 9 in [1]
        m_bene_reg = m_bene_ilm/(6*self.regHeadGrade) #Eq 10 in [1]
        m_gangue = regolithMass - m_bene_reg

        #Calculate mass of water and oxygen
        m_H2O = m_bene_ilm*0.47*(18.01528/151.71) #Eq 13 in [1]
        m_O2 = (m_H2O*31.999)/(2*18.01528) # Eq 16 in [1]

        #Get simulation to yield for however long is required to process the amount of regolith given to the plant. Assume that the plant has the capability to hold any amount of regolith that could reasonably be given to it.
        yieldLength = regolithMass/self.processingRate

        #Energy Consumption Attributes
        E_exc = self.excavationEnergyCoeff*regolithMass #Excavation Energy, kWh, Eq 5 in [1]
        E_trans = self.transportEnergyCoeff*regolithMass*transportDist #Transportation Energy, kWh, Eq 8 in [1]

        E_bene = ((regolithMass*self.lg*self.liftHeight)/3600000) + m_gangue*(3.6*10**-4)*self.gangueTransportDist #Beneficiation Energy, kWh, Eq 11 in [1], note that the first cosntant of 1 represents the height that the regolith needs to be lifted for beneficiation in meters, the second constant of 1 represents the distance that the waste material (gangue) is transported in km
        E_reactor =  self.reactorEnergyCoeff * m_bene_reg #Energy Required By Reactor, kWh, Eq 14 in [1] (took the mean value of 0.385)
        E_electro = self.electrolysisEnergyCoeff*m_H2O #Energy for Electrolysis, kWh, Eq 18 in [1]
        E_liq = self.liquefactionEnergyCoeff*m_O2 #Liquefaction, kWh, Eq. 21 in [1]

        E_storage = 0 #Storage Energy

        processingEnergyRequired = E_exc+E_trans+E_bene+E_reactor+E_electro+E_liq
        self.totalEnergyConsumed += processingEnergyRequired
        #print("Total Energy Required: " + str(totalEnergyRequired))
        #print("LOX Produced: " + str(self.LOXStored))

        self.processingUptime += yieldLength #Add processing time to total hours the plant is running.

        yield system.timeout(yieldLength)
        print(f"[{system.now:.2f} hr] ISRU Plant produced {generatedLOX} kg of LOX from {regolithMass} kg of Regolith using {processingEnergyRequired} kWh of Energy. There is now {self.LOXStored} kg of LOX stored, and {self.totalEnergyConsumed} kWh has been consumed.")

    def getLoggingAttributes(self):
        attr = {
            "Name": self.name,
            "processingRate": self.processingRate,
            "regHeadGrade": self.regHeadGrade,
            "LOX_Stored": self.LOXStored,
            "total_energy_consumed": self.totalEnergyConsumed,

            "excavationEnergyCoeff": self.excavationEnergyCoeff,
            "transportEnergyCoeff": self.transportEnergyCoeff,
            "liftHeight": self.liftHeight,
            "gangueTransportDist": self.gangueTransportDist,
            "reactorEnergyCoeff": self.reactorEnergyCoeff,
            "electrolysisEnergyCoeff": self.electrolysisEnergyCoeff,
            "liquefactionEnergyCoeff": self.liquefactionEnergyCoeff,

            "processing_uptime": self.processingUptime,
            "total_LOX_production": self.totalLOXProduction, 
            "regolith_recieved": self.regolithRecieved
        }
        return attr


#-----------------------------------------------------------------------------------------------------------------------------------------
# re-written


# """
# Models an ISRU Plant that uses Hydrogen Reduction to generate LOX from lunar regolith.

# References:
# [1] https://doi.org/10.1073/pnas.2306146122 
# """
# import simpy
# from typing import Any, Dict, Generator

# class ISRUPlant:
#     """
#     Discrete-event simulation model of an ISRU plant that produces liquid oxygen
#     (LOX) from lunar regolith via hydrogen reduction.

#     The model tracks:
#     - regolith throughput
#     - LOX production and on-site storage
#     - cumulative energy consumption
#     - cumulative processing uptime

#     Parameters are initialized from an attribute dictionary, which is expected
#     to contain plant configuration values and energy model coefficients.

#     Reference:
#     [1] https://doi.org/10.1073/pnas.2306146122
#     """

#     def __init__(
#         self,
#         system: simpy.Environment,
#         name: str,
#         attribute_dict: Dict[str, Any],
#     ) -> None:
#         self.system = system
#         self.name = name
#         self._initialize_attributes(attribute_dict)

#     def _initialize_attributes(self, attribute_dict: Dict[str, Any]) -> None:
#         """
#         Initialize plant parameters and simulation state from an attribute dictionary.
#         """
#         self.processing_rate = attribute_dict["processingRate"]              # kg/hr
#         self.regolith_head_grade = attribute_dict["regHeadGrade"]           # mass fraction / wt%
#         self.lox_stored = attribute_dict["LOXStored"]                       # kg
#         self.lunar_gravity = attribute_dict["lunarGravity"]                 # m/s^2
#         self.total_energy_consumed = attribute_dict["totalEnergyConsumed"]  # kWh

#         self.excavation_energy_coeff = attribute_dict["excavationEnergyCoeff"]
#         self.transport_energy_coeff = attribute_dict["transportEnergyCoeff"]
#         self.lift_height = attribute_dict["liftHeight"]                     # m
#         self.gangue_transport_dist = attribute_dict["gangueTransportDist"]  # km
#         self.reactor_energy_coeff = attribute_dict["reactorEnergyCoeff"]
#         self.electrolysis_energy_coeff = attribute_dict["electrolysisEnergyCoeff"]
#         self.liquefaction_energy_coeff = attribute_dict["liquefactionEnergyCoeff"]

#         self.processing_uptime = 0.0
#         self.total_lox_production = 0.0
#         self.regolith_received = 0.0

#     def process_regolith(
#         self,
#         regolith_mass: float,
#         transport_dist: float = 1.0,
#     ) -> Generator[Any, None, None]:
#         """
#         Process a batch of regolith and update plant state.

#         Parameters
#         ----------
#         regolith_mass : float
#             Mass of regolith delivered to the plant [kg].
#         transport_dist : float, optional
#             Transport distance associated with the delivered regolith [km].

#         Yields
#         ------
#         SimPy timeout event
#             Represents the simulated processing time required for the batch.
#         """
#         # Oxygen extraction and LOX production
#         extracted_lox_fraction = (
#             0.51 * 0.47 * 31.999 * self.regolith_head_grade
#         ) / (2 * 151.71)  # Eq. (1) in [1]

#         kg_lox_per_hour = extracted_lox_fraction * self.processing_rate
#         generated_lox = extracted_lox_fraction * regolith_mass

#         self.lox_stored += generated_lox
#         self.total_lox_production += generated_lox
#         self.regolith_received += regolith_mass

#         # Beneficiation and waste stream calculations
#         m_bene_ilm = regolith_mass * 0.505 * self.regolith_head_grade       # Eq. (9)
#         m_bene_reg = m_bene_ilm / (6 * self.regolith_head_grade)            # Eq. (10)
#         m_gangue = regolith_mass - m_bene_reg

#         # Water and oxygen mass calculations
#         m_h2o = m_bene_ilm * 0.47 * (18.01528 / 151.71)                     # Eq. (13)
#         m_o2 = (m_h2o * 31.999) / (2 * 18.01528)                            # Eq. (16)

#         # Processing time
#         processing_duration = regolith_mass / self.processing_rate          # hr

#         # Energy model
#         e_exc = self.excavation_energy_coeff * regolith_mass
#         e_trans = self.transport_energy_coeff * regolith_mass * transport_dist
#         e_bene = (
#             (regolith_mass * self.lunar_gravity * self.lift_height) / 3_600_000
#             + m_gangue * (3.6e-4) * self.gangue_transport_dist
#         )                                                                   # Eq. (11)
#         e_reactor = self.reactor_energy_coeff * m_bene_reg                  # Eq. (14)
#         e_electro = self.electrolysis_energy_coeff * m_h2o                  # Eq. (18)
#         e_liq = self.liquefaction_energy_coeff * m_o2                       # Eq. (21)

#         processing_energy_required = (
#             e_exc + e_trans + e_bene + e_reactor + e_electro + e_liq
#         )

#         self.total_energy_consumed += processing_energy_required
#         self.processing_uptime += processing_duration

#         yield self.system.timeout(processing_duration)

#         print(
#             f"[{self.system.now:.2f} hr] {self.name} processed "
#             f"{regolith_mass:.2f} kg regolith, produced {generated_lox:.2f} kg LOX, "
#             f"consumed {processing_energy_required:.2f} kWh, and now stores "
#             f"{self.lox_stored:.2f} kg LOX."
#         )

#     def get_logging_attributes(self) -> Dict[str, Any]:
#         """
#         Return a dictionary of plant attributes and cumulative metrics for logging.
#         """
#         return {
#             "name": self.name,
#             "processing_rate": self.processing_rate,
#             "regolith_head_grade": self.regolith_head_grade,
#             "lox_stored": self.lox_stored,
#             "total_energy_consumed": self.total_energy_consumed,
#             "excavation_energy_coeff": self.excavation_energy_coeff,
#             "transport_energy_coeff": self.transport_energy_coeff,
#             "lift_height": self.lift_height,
#             "gangue_transport_dist": self.gangue_transport_dist,
#             "reactor_energy_coeff": self.reactor_energy_coeff,
#             "electrolysis_energy_coeff": self.electrolysis_energy_coeff,
#             "liquefaction_energy_coeff": self.liquefaction_energy_coeff,
#             "processing_uptime": self.processing_uptime,
#             "total_lox_production": self.total_lox_production,
#             "regolith_received": self.regolith_received,
#         }